version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./:/docker/
    volumes_from:
      - storage
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage
  sonarqube:
    build:
      context: .
      dockerfile: docker/sonarqube/Dockerfile
    ports:
      - "9000:9000"
      - "443"